language: php

php:
  - 5.3
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: 5.4

before_script:
  - /home/travis/.phpenv/versions/5.3/bin/composer self-update
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - /home/travis/.phpenv/versions/hhvm/bin/composer self-update
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
